baseurl: /
languageCode: ru-RU
defaultContentLanguage: ru
theme: terminal
paginate: 5

params:
  contentTypeName: posts
  themeColor: green
  showMenuItems: 2
  showLanguageSelector: false
  fullWidthTheme: true
  centerTheme: true
  showLastUpdated: false
  twitter:
    creator: ''
    site: ''

languages:
  ru:
    languageName: Russian
    title: Anver Bogatov
    subtitle: 'Мой личный островок в океане Интернета'
    owner: ''
    keywords: ''
    copyright: ''
    menuMore: Показать ещё
    readMore: Читать дальше
    readOtherPosts: Другие статьи
    newerPosts: Новые статьи
    olderPosts: Старые статьи
    missingContentMessage: Страница не найдена...
    missingBackButtonLabel: Назад на главную страницу
    params:
      logo:
        logoText: Anver Bogatov
        logoHomeLink: /
    menu:
      main:
        - identifier: about
          name: Обо мне
          url: /about
        - identifier: showcase
          name: Статьи
          url: /showcase

